# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 613)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/youtube-logo-circle2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("selection-color:black;\n"
"selection-background-color:rgb(218, 218, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 811, 611))
        self.frame_4.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setGeometry(QtCore.QRect(5, 5, 801, 601))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(72, 72, 72)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 801, 31))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color:rgb(49, 49, 49)\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_exit = QtWidgets.QPushButton(self.frame_2)
        self.btn_exit.setGeometry(QtCore.QRect(770, 0, 31, 31))
        font = QtGui.QFont()
        font.setFamily("TeamViewer15")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    background-color:rgb(72, 72, 72);\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.btn_exit.setFlat(True)
        self.btn_exit.setObjectName("btn_exit")
        self.btn_min = QtWidgets.QPushButton(self.frame_2)
        self.btn_min.setGeometry(QtCore.QRect(740, 0, 31, 31))
        font = QtGui.QFont()
        font.setFamily("TeamViewer15")
        font.setPointSize(22)
        self.btn_min.setFont(font)
        self.btn_min.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_min.setStyleSheet("QPushButton {\n"
"    background-color:rgb(72, 72, 72);\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.btn_min.setFlat(True)
        self.btn_min.setObjectName("btn_min")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 135, 801, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(290, 10, 221, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/icon-white-red.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(13, 210, 781, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.input_url = QtWidgets.QLineEdit(self.frame)
        self.input_url.setGeometry(QtCore.QRect(150, 270, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_url.setFont(font)
        self.input_url.setStyleSheet("\n"
"    padding:5px;\n"
"    border: 3px solid black;\n"
"    background-color:white;\n"
"    border-width: 3px 0px 3px 3px;\n"
"")
        self.input_url.setObjectName("input_url")
        self.combo_file_type = QtWidgets.QComboBox(self.frame)
        self.combo_file_type.setGeometry(QtCore.QRect(150, 330, 161, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.combo_file_type.setFont(font)
        self.combo_file_type.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.combo_file_type.setStyleSheet("QComboBox {\n"
"    padding:5px;\n"
"    border: 2px solid black;\n"
"    background-color:white;\n"
"}\n"
"\n"
"QListView {\n"
"    background-color:white;\n"
"}")
        self.combo_file_type.setObjectName("combo_file_type")
        self.combo_file_type.addItem("")
        self.combo_file_type.addItem("")
        self.combo_file_type.addItem("")
        self.btn_dl = QtWidgets.QPushButton(self.frame)
        self.btn_dl.setGeometry(QtCore.QRect(520, 330, 141, 37))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.btn_dl.setFont(font)
        self.btn_dl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_dl.setStyleSheet("QPushButton {\n"
"    background-color:rgb(72, 72, 72);\n"
"    border: 2px solid white;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:rgb(255, 0, 0);\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color:white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/download-icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_dl.setIcon(icon1)
        self.btn_dl.setIconSize(QtCore.QSize(30, 20))
        self.btn_dl.setObjectName("btn_dl")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 566, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_open_dl = QtWidgets.QPushButton(self.frame)
        self.btn_open_dl.setGeometry(QtCore.QRect(323, 330, 181, 37))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.btn_open_dl.setFont(font)
        self.btn_open_dl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_open_dl.setStyleSheet("QPushButton {\n"
"    background-color:rgb(72, 72, 72);\n"
"    border: 2px solid white;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:rgb(255, 0, 0);\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color:white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/folder-icon-30.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_open_dl.setIcon(icon2)
        self.btn_open_dl.setObjectName("btn_open_dl")
        self.btn_clear = QtWidgets.QPushButton(self.frame)
        self.btn_clear.setGeometry(QtCore.QRect(620, 270, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_clear.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(255, 255, 255);\n"
"    border: 3px solid black;\n"
"    border-width: 3px 3px 3px 0px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.btn_clear.setFlat(True)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_dl_2 = QtWidgets.QPushButton(self.frame)
        self.btn_dl_2.setGeometry(QtCore.QRect(20, 555, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(11)
        self.btn_dl_2.setFont(font)
        self.btn_dl_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_dl_2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 0, 0);\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:rgb(255, 71, 65);\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color:white;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/question.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_dl_2.setIcon(icon3)
        self.btn_dl_2.setIconSize(QtCore.QSize(18, 18))
        self.btn_dl_2.setObjectName("btn_dl_2")
        self.btn_dl_4 = QtWidgets.QPushButton(self.frame)
        self.btn_dl_4.setGeometry(QtCore.QRect(650, 555, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(11)
        self.btn_dl_4.setFont(font)
        self.btn_dl_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_dl_4.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 0, 0);\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:rgb(255, 71, 65);\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color:white;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/youtube-logo-white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_dl_4.setIcon(icon4)
        self.btn_dl_4.setIconSize(QtCore.QSize(18, 18))
        self.btn_dl_4.setObjectName("btn_dl_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Video & Audio Downloader"))
        self.btn_exit.setText(_translate("MainWindow", "x"))
        self.btn_min.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Video / Audio Downloader"))
        self.input_url.setPlaceholderText(_translate("MainWindow", "Place your video link here"))
        self.combo_file_type.setItemText(0, _translate("MainWindow", "Select file type"))
        self.combo_file_type.setItemText(1, _translate("MainWindow", "Video"))
        self.combo_file_type.setItemText(2, _translate("MainWindow", "Audio"))
        self.btn_dl.setText(_translate("MainWindow", " Download "))
        self.label_3.setText(_translate("MainWindow", "© 2022 Eli Bautista Softwares"))
        self.btn_open_dl.setText(_translate("MainWindow", " Open Downloads"))
        self.btn_clear.setText(_translate("MainWindow", "x"))
        self.btn_dl_2.setText(_translate("MainWindow", "How it works ?"))
        self.btn_dl_4.setText(_translate("MainWindow", "Open YouTube"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
